title: Residência BRISA
description: > # this means to ignore newlines until "baseurl:"
  Projeto Residência em TIC da BRISA - UnB FGA
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://template-pages-lappis.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: 
author-img: lappis.png
about-author: Residência BRISA
social-email: caguiar@unb.br

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
